:set number
:set relativenumber
:set autoindent
:set tabstop=8
:set shiftwidth=4
:set smarttab
:set softtabstop=4
:set nowrap
:set mouse=a
:set noswapfile
:set nobackup
:set undodir=~/.nv/undodir
:set undofile
:set incsearch
:set background=dark
:set splitright
:set splitbelow
:set wildmode=longest,list
