require('setpkg/nvim-tree')
require('setpkg/lualine')
require('setpkg/compe')
require('setpkg/lspkind')
require('setpkg/kommentary')
require('setpkg/bufferline')
require('setpkg/neoscroll')
require('setpkg/which-key')
